job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-storytelling
    WP_DB_NAME_PREFIX: planet4-storytel_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: storytelling-dev.greenpeace.org
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-storytelling
    NEWRELIC_APPNAME: P4 Storytelling Development
    WP_DB_NAME: planet4-storytel_wordpress_develop
    WP_STATELESS_BUCKET: planet4-storytelling-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: storytelling-stage.greenpeace.org
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: storytelling
    HELM_RELEASE: planet4-storytelling-release
    NEWRELIC_APPNAME: P4 Storytelling Release
    WP_DB_NAME: planet4-storytel_wordpress_release
    WP_STATELESS_BUCKET: planet4-storytelling-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: storytelling.greenpeace.org
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: storytelling
    HELM_RELEASE: planet4-storytelling-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Storytelling Production
    WP_DB_NAME: planet4-storytel_wordpress_master
    WP_STATELESS_BUCKET: planet4-storytelling-stateless